import {chromium} from 'playwright';
const mods = process.argv[2] || 'sky,gi,terrain,buildings,rail,trains,vegetation';
const URL=`http://127.0.0.1:5601/static/world/dev/solo.html?mods=${mods}&cam=far&time=16&hud=0&quality=ultra`;
const b=await chromium.launch({headless:true,channel:'chromium',args:['--use-angle=metal','--enable-unsafe-swiftshader']});
const p=await b.newPage({viewport:{width:1280,height:720}});
const logs=[];
p.on('console',m=>{const t=m.text(); if(/vegetation/.test(t)) logs.push(m.type()+': '+t);});
p.on('pageerror',e=>logs.push('PAGEERROR '+String(e).slice(0,300)));
await p.goto(URL,{waitUntil:'load',timeout:90000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:90000});
await p.waitForTimeout(9000);
console.log(logs.join('\n'));
await b.close();
