import {chromium} from 'playwright';
const b = await chromium.launch({headless:true, channel:'chromium'});
const p = await b.newPage();
p.on('console', m => console.log('[console:'+m.type()+']', m.text()));
p.on('pageerror', e => console.log('[pageerror]', String(e).slice(0,600)));
p.on('requestfailed', r => console.log('[reqfail]', r.url(), r.failure()?.errorText));
p.on('response', r => { if (r.status() >= 400) console.log('[http '+r.status()+']', r.url()); });
await p.goto(process.argv[2], {waitUntil:'load'});
await p.waitForTimeout(2500);
console.log('__lemWorld:', await p.evaluate(() => typeof window.__lemWorld));
console.log('err box:', await p.evaluate(() => document.getElementById('err')?.textContent?.slice(0,800)));
await b.close();
