import {chromium} from 'playwright';
const b=await chromium.launch({headless:true,channel:'chromium',args:['--use-angle=metal','--ignore-gpu-blocklist']});
const p=await (await b.newContext({viewport:{width:1600,height:950}, deviceScaleFactor:1})).newPage();
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,140)));
await p.goto('http://127.0.0.1:5612/floor',{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>!!window.__lemWorld,null,{timeout:45000});
await p.waitForTimeout(14000);
await p.click('#btnQuality');
await p.waitForTimeout(600);
console.log('dialog open:', await p.evaluate(()=>document.getElementById('qualDlg').open));
console.log('resolution options:', await p.evaluate(()=>[...document.querySelectorAll('#resList input[name=res]')].map(i=>i.value)));
console.log('reads now  :', await p.evaluate(()=>document.getElementById('resNow').textContent));
await p.click('#resList input[value=full]');
await p.waitForTimeout(1200);
console.log('after full :', await p.evaluate(()=>document.getElementById('resNow').textContent));
await p.screenshot({path:'/tmp/floor-qual.png'});
if(errs.length) console.log('ERRORS:',errs.slice(0,3)); else console.log('no page errors');
await b.close();
