import {chromium} from 'playwright';
import fs from 'node:fs';
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal','--enable-unsafe-swiftshader']});
const p = await b.newPage({viewport:{width:1920,height:1080}});
await p.goto(process.argv[2],{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:45000});
await p.waitForTimeout(11000);
const shot = async n => { await p.waitForTimeout(1800);
  fs.writeFileSync('/Users/rynatical/LAB-lem/scratchpad/shots/ABL-'+n+'.png', await p.screenshot()); };
await shot('base');
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.userData.lem.uVegGain.value = 0.0; });
await shot('albedo0');
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.envMapIntensity = 0; v.matFar.userData.lemEnvBase = 0; v.matFar.needsUpdate = true; });
await shot('noenv');
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.userData.lem.uVegSSS.value = 0; v.matFar.userData.lem.uVegWrap.value = 0; });
await shot('nosss');
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.wireframe = true; v.matFar.needsUpdate = true; });
await shot('wire');
await b.close(); console.log('ok');
