import {chromium} from 'playwright';
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal','--enable-unsafe-swiftshader']});
const p = await b.newPage({viewport:{width:1280,height:720}});
let seen=0;
p.on('pageerror', e => { if(seen++<2) console.log('PAGEERR', e.stack ? e.stack.slice(0,900) : String(e)); });
p.on('console', m=>{ const t=m.text(); if(/vegetation|terrain\]/.test(t)) console.log('['+m.type()+']',t.slice(0,220)); });
await p.goto('http://127.0.0.1:5601/static/world/dev/solo.html?cam=wide&time=16&hud=0',{waitUntil:'load',timeout:90000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:90000});
await p.waitForTimeout(4000);
await b.close();
