import {chromium} from 'playwright';
import fs from 'fs';
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal','--enable-unsafe-swiftshader']});
const p = await b.newPage({viewport:{width:1920,height:1080}});
await p.goto(process.argv[2],{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:45000});
await p.waitForTimeout(11000);
fs.writeFileSync('/Users/rynatical/LAB-lem/scratchpad/shots/HD-on.png', await p.screenshot());
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation'); v.group.visible=false; });
await p.waitForTimeout(1500);
fs.writeFileSync('/Users/rynatical/LAB-lem/scratchpad/shots/HD-off.png', await p.screenshot());
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation'); v.group.visible=true;
  for (const e of v.trees) e.far.visible=false; });
await p.waitForTimeout(1500);
fs.writeFileSync('/Users/rynatical/LAB-lem/scratchpad/shots/HD-nofar.png', await p.screenshot());
await b.close();
