import {chromium} from 'playwright';
import fs from 'node:fs';
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal','--enable-unsafe-swiftshader']});
const p = await b.newPage({viewport:{width:1920,height:1080}});
await p.goto(process.argv[2],{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:45000});
await p.waitForTimeout(11000);
const shot = async n => { await p.waitForTimeout(1800);
  fs.writeFileSync('/Users/rynatical/LAB-lem/scratchpad/shots/SL-'+n+'.png', await p.screenshot()); };
await shot('base');
await p.evaluate(()=>{ const u=window.__lemWorld.subsystems.get('vegetation').matFar.userData.lem;
  u.uVegAlphaBias.value = 0; u.uVegDither.value = 0; });
await shot('bias0');
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.alphaTest = 0.72; v.matFar.needsUpdate = true; });
await shot('cut72');
await p.evaluate(()=>{ const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.map.anisotropy = 1; v.matFar.map.needsUpdate = true; v.matFar.needsUpdate=true; });
await shot('aniso1');
await b.close(); console.log('ok');
