import {chromium} from 'playwright';
import fs from 'node:fs';
let URL = process.argv[2] + '&quality=ultra';
const O = process.argv[3];
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal']});
const p = await b.newPage({viewport:{width:1920,height:1080}});
await p.goto(URL,{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:60000});
await p.waitForTimeout(9000);
const shot=async n=>{await p.waitForTimeout(1300); fs.writeFileSync(`${O}-${n}.png`, await p.screenshot()); console.log('shot',n);};
const ev=(f,a)=>p.evaluate(f,a);
// near tier hidden throughout so the far cards are what is photographed
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  for(const e of v.trees) if(e.near) e.near.visible=false;});
await shot('far');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.userData.lem.uVegAlphaBias.value=0;});
await shot('bias0');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.userData.lem.uVegAlphaBias.value=0.34;
  v.matFar.wireframe=true; v.matFar.needsUpdate=true;});
await shot('wire');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.wireframe=false; v.matFar.color.setRGB(0,0,0); v.matFar.needsUpdate=true;});
await shot('black');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  v.matFar.color.setRGB(1,1,1); v.matFar.needsUpdate=true;
  v.matFar.userData.lem.uVegSSS.value=0; v.matFar.userData.lem.uVegWrap.value=0;
  v.matFar.envMapIntensity=0;});
await shot('black-nosss');
await b.close();
