import {chromium} from 'playwright';
import fs from 'node:fs';
let URL = process.argv[2] + '&quality=ultra';
const O = process.argv[3];
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal']});
const p = await b.newPage({viewport:{width:1920,height:1080}});
await p.goto(URL,{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:60000});
await p.waitForTimeout(9000);
const shot=async n=>{await p.waitForTimeout(1300); fs.writeFileSync(`${O}-${n}.png`, await p.screenshot()); console.log('shot',n);};
const ev=(f,a)=>p.evaluate(f,a);
await shot('all');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  for(const e of v.trees) if(e.far) e.far.visible=false;});
await shot('nofar');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  for(const e of v.trees){ if(e.far) e.far.visible=true; if(e.near) e.near.visible=false;}});
await shot('nonear');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  for(const e of v.trees) if(e.near) e.near.visible=true;});
// kill the two glow terms
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  for(const m of v.materials){const L=m.userData?.lem; if(!L) continue;
    if(L.uVegSSS) L.uVegSSS.value=0; if(L.uVegWrap) L.uVegWrap.value=0;}});
await shot('nosss');
await ev(()=>{const v=window.__lemWorld.subsystems.get('vegetation');
  for(const m of v.materials){ m.envMapIntensity=0; m.needsUpdate=true; }});
await shot('nosss-noenv');
await b.close();
