import {chromium} from 'playwright';
import fs from 'node:fs';
const b = await chromium.launch({headless:true, channel:'chromium', args:['--use-angle=metal','--enable-unsafe-swiftshader']});
const p = await b.newPage({viewport:{width:1920,height:1080}});
await p.goto(process.argv[2],{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__worldReady===true,null,{timeout:45000});
await p.waitForTimeout(11000);
const shot = async n => { await p.waitForTimeout(1600);
  fs.writeFileSync('/Users/rynatical/LAB-lem/scratchpad/shots/W2-'+n+'.png', await p.screenshot()); };
await shot('all');
await p.evaluate(()=>{ window.__lemWorld.subsystems.get('vegetation').group.visible=false; });
await shot('none');
await b.close(); console.log('ok');
