import {chromium} from 'playwright';
const b = await chromium.launch({headless:true, channel:'chromium'});
const p = await b.newPage({viewport:{width:1920,height:1080}});
const msgs = [];
p.on('console', m => { if (m.type()!=='log') msgs.push(m.type()+': '+m.text()); });
p.on('pageerror', e => msgs.push('pageerror: '+e.message));
await p.goto(process.argv[2], {waitUntil:'load'});
await p.waitForFunction(() => window.__worldReady === true, null, {timeout:60000});
await p.waitForTimeout(6000);
await p.evaluate(() => { window.__lemWorld.setTimeOfDay(19.5); });
await p.waitForTimeout(1500);
await p.evaluate(() => { window.__lemWorld.setWeather({preset:'storm',rain:1,wetness:1,cloud:1,fog:0.6,wind:0.9}); });
await p.waitForTimeout(1500);
await p.evaluate(() => { window.__lemWorld.setTimeOfDay(2); });
await p.waitForTimeout(1500);
console.log(msgs.length ? msgs.join('\n') : 'no warnings or errors');
await b.close();
